include:
  - local: '/ci/templates/bounded-context/gitlab-ci.yml'

variables:
  CONTEXT_DIR: "services/bounded-contexts/compliance-context"
  CONTEXT_README: "services/bounded-contexts/compliance-context/README.md"
  CONTEXT_MANIFEST: "services/bounded-contexts/compliance-context/REPO_MANIFEST.md"
  CONTEXT_OPENAPI: "api/openapi/compliance-context.yaml"
